# Generated by Django 3.2.4 on 2021-06-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=50)),
                ('patientname', models.CharField(max_length=50)),
                ('doctoremail', models.EmailField(max_length=254)),
                ('patientemail', models.EmailField(max_length=254)),
                ('appointmentdate', models.DateField()),
                ('appointmenttime', models.TimeField()),
                ('symptoms', models.TextField()),
                ('prescriptiom', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('bloodgroup', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('speciality', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('bloodgroup', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
